eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:18611/eureka/
server:
  port: 18618
spring:
  application:
    name: service-sleuth
  zipkin:
    base-url: http://localhost:18617
  sleuth:
    sampler:
      percentage: 1.0
      