eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18611/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 18612
spring:
  application:
    name: service-zuul

zuul:
  routes:
    rest-demo: /rest/**
  ignored-services: rest-demo,xxx-service
security:
  oauth2:
    client:
      access-token-uri: http://10.10.8.2:9030/uaa/oauth/token ##网关的地址
      user-authorization-uri: http://10.10.8.2:9030/uaa/oauth/authorize
    resource:
      user-info-uri:  http://10.10.8.2:9030/uaa/user
      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
